### ISSUE TITLE
Attempted to modify LootPool after being frozen

### ISSUE THREAD

**Issue by gbui** [gbui/SimpleTreeDrops#1]
Snippet from MadRatSRP/CRASHLOGS#1:
````
[00:42:37] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.LootTableLoadEvent@1ee698d:
java.lang.RuntimeException: Attempted to modify LootPool after being frozen!
	at net.minecraft.world.storage.loot.LootPool.checkFrozen(LootPool.java:98) ~[bci.class:?]
	at net.minecraft.world.storage.loot.LootPool.setRolls(LootPool.java:104) ~[bci.class:?]
	at io.github.gbui.simpletreedrops.CustomLootHelper.loadCustomLoot(CustomLootHelper.java:60) ~[CustomLootHelper.class:?]
	at io.github.gbui.simpletreedrops.SimpleTreeDrops.onLoadLootTable(SimpleTreeDrops.java:85) ~[SimpleTreeDrops.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_424_SimpleTreeDrops_onLoadLootTable_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:688) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1164) [ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148) [bcn$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71) [bcn$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52) [bcn$a.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [guava-17.0.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39) [bcn.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48) [bcn.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34) [bcn.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:151) [lw.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:81) [cch.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
````

**Comment by gbui** [comment]
Dev build: [SimpleTreeDrops-1.11.2-1.0.3.1-alpha.1.jar.zip](https://github.com/gbui/SimpleTreeDrops/files/1104039/SimpleTreeDrops-1.11.2-1.0.3.1-alpha.1.jar.zip)

**Comment by GeebsRilie** [comment]
yup just about to write this.
Exception caught during firing event net.minecraftforge.event.LootTableLoadEvent@15fb6073:
java.lang.RuntimeException: Attempted to modify LootPool after being frozen!
	at net.minecraft.world.storage.loot.LootPool.checkFrozen(LootPool.java:98) ~[bci.class:?]
	at net.minecraft.world.storage.loot.LootPool.setRolls(LootPool.java:104) ~[bci.class:?]
	at io.github.gbui.simpletreedrops.CustomLootHelper.loadCustomLoot(CustomLootHelper.java:60) ~[CustomLootHelper.class:?]
	at io.github.gbui.simpletreedrops.SimpleTreeDrops.onLoadLootTable(SimpleTreeDrops.java:85) ~[SimpleTreeDrops.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_508_SimpleTreeDrops_onLoadLootTable_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:688) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1162) [ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148) [bcn$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71) [bcn$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52) [bcn$a.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [guava-17.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [guava-17.0.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39) [bcn.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48) [bcn.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34) [bcn.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:151) [lw.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:86) [cch.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
[23:04:55] [Server thread/ERROR]: Index: 5 Listeners:

**Comment by xAlicatt** [comment]
Getting the same error. This is MP server side only though. Client load up seems fine. I'm running Sponge server software, can't speak for the others here, but I'm going to assume they have a similar setup.

Will try the dev build and report back.

**Comment by GeebsRilie** [comment]
I didnt try the dev build yet. Thanks for showing me.

**Comment by gbui** [comment]
@xAlicatt: What version(s) of Forge are installed on the server and on the client? Also could you provide the full log of the server error? The log file should be at `logs/fml-client-latest.log`

@GeebsRilie: Any improvement? If not, could you follow the above instructions as well? (I hope I'm not being too bossy!) As for the leaf drops, it's probably not Nests or the other mods. This error seems to be caused by modifying loot tables, but I can't figure out the exact reason.

**Comment by GeebsRilie** [comment]
13.20.0.2366 forge

This is a huge log to wade thru, I am sorry, We are making a modpack.

[https://drive.google.com/open?id=0B2Xij7aGuz17OFFDWGh5X2ttaXc]

**Comment by gbui** [comment]
Hm... The log says Simple Tree Drops 1.0.3 is installed. Did you try 1.0.3.1-alpha.2? Does it also cause an error?

**Comment by GeebsRilie** [comment]
I did try that one as well same error

**Comment by xAlicatt** [comment]
Ok, here's the latest I have for you using `SimpleTreeDrops-1.11.2-1.0.3.1-alpha.2.jar` and `spongeforge-1.10.2-2281-5.2.0-BETA-2424.jar` which is for Forge 2281

Crash report: https://gist.github.com/xAlicatt/ee174cb0d00e4292f91c9d9bdf073143

Client loads fine, server does not.

**Comment by gbui** [comment]
@GeebsRilie: I'm currently trying version 1.06 F of your modpack to try to recreate the error. (Which version of Faucets and Filters are you using? I got 1.0.1 for 1.11.2.)

@xAlicatt: Weird, it seems that particular error is caused by Ender IO.

**Comment by xAlicatt** [comment]
@gbui server loads fine without your mod

**Comment by gbui** [comment]
I'll look into it.

**Comment by xAlicatt** [comment]
@gbui Just tried to make a singleplayer world with your mod installed and I'm getting the same error, so it's nothing to do with the server software afterall.

Here is that crash report: https://gist.github.com/xAlicatt/90b6ff539420d2e02534e27eebca1cbc

**Comment by gbui** [comment]
Hm... If it's not any trouble, could you take out Ender IO and see if it still errors?

**Comment by xAlicatt** [comment]
You are welcome to download my pack and test it yourself. My pack has over 270 mods currently and, yes, it is a lot of trouble to disable EIO and the mods that depend on it to test on my multiplayer server. I run the risk of corrupting our map, and would rather not do so. It's much easier for me to just not use your mod, since I have no problems without it :P

https://minecraft.curseforge.com/projects/jakspack-1-10-2/files

**Comment by gbui** [comment]
Ah, okay.

Unless I can pick out the specific mods that are crashing with Simple Tree Drops, I'll have to test these modpacks on a better computer, which will take some time. (Just now I rebooted this computer after crashing from Hardened Realism lol.)

I have to agree with you that it'd be much easier to not use this mod. As a last resort, could you try disabling loot in the config file? It should at `config/simpletreedrops.cfg`. (I noticed you're on 1.10.2, so make sure to replace `SimpleTreeDrops-1.11.2-1.0.3.1-alpha.2.jar` with [`SimpleTreeDrops-1.10.2-1.0.3.jar`](https://minecraft.curseforge.com/projects/simple-tree-drops/files/2441968).)

**Comment by xAlicatt** [comment]
The EIO error was erroneous, since I'm not having it reference EIO using the 1.10.2 version of your mod. In the process of testing with loot turned off to see if I'm still getting the lootpool after frozen issue.

**Comment by xAlicatt** [comment]
Loads with loot turned off. :)

**Comment by xAlicatt** [comment]
I will try it on my MP server now....and get back to you.

**Comment by gbui** [comment]
All right. (Note: Discussion regarding EIO should be redirected to issue #3.)

**Comment by xAlicatt** [comment]
Was able to successfully load our 1.10.2 (Forge 2281) MP server with STD installed with loot disabled. Will be looking forward to a fix for that :) Thanks for the help!

**Comment by WenXin20** [comment]
I got this [crash](https://pastebin.com/kmMW9yZT) and it mentions the mod Lootbags v2.3.9. I am using Forge 2316

**Comment by gbui** [comment]
Hi, could you try disabling loot in the config file? It should at `.minecraft/config/simpletreedrops.cfg`.
