### ISSUE TITLE
[1.12-1.0.4] crash on game start :  Attempted to modify LootPool after being frozen!

### ISSUE THREAD

**Issue by PrinceOfAmber** [gbui/SimpleTreeDrops#5]
java.lang.RuntimeException: Attempted to modify LootPool after being frozen!
	at net.minecraft.world.storage.loot.LootPool.checkFrozen(LootPool.java:98) ~[bfo.class:?]
	at net.minecraft.world.storage.loot.LootPool.setRolls(LootPool.java:104) ~[bfo.class:?]
	at io.github.gbui.simpletreedrops.CustomLootHelper.loadCustomLoot(CustomLootHelper.java:51) ~[CustomLootHelper.class:?]
	at io.github.gbui.simpletreedrops.SimpleTreeDrops.onLoadLootTable(SimpleTreeDrops.java:93) ~[SimpleTreeDrops.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_363_SimpleTreeDrops_onLoadLootTable_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:653) [ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1134) [ForgeHooks.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:156) [bft$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72) [bft$a.class:?]
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53) [bft$a.class:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [guava-21.0.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [guava-21.0.jar:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:40) [bft.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:49) [bft.class:?]
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35) [bft.class:?]
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:154) [om.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:82) [chb.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:196) [chb.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by gbui** [comment]
Hi, could you try disabling loot in the config file? It should at `.minecraft/config/simpletreedrops.cfg`.

**Comment by PrinceOfAmber** [comment]
Yes confirmed.  If i set all the loot sections to false then the game loads. to be precise


loot {
    B:chests.igloo_chest=false
    B:chests.spawn_bonus_chest=false
    B:chests.stronghold_corridor=false
    B:chests.stronghold_crossing=false
    B:chests.village_blacksmith=false
}

rest of the config unchanged.
And the fruit shows up in JEI

**Comment by PrinceOfAmber** [comment]
How do you add loot, are you using the loot table load event?


This is what I do 

https://github.com/PrinceOfAmber/Cyclic/blob/195222b6dd237b901cffca1af5b9b394c161d490/src/main/java/com/lothrazar/cyclicmagic/module/LootTableModule.java#L41

**Comment by gbui** [comment]
Yes, I use the loot table event; it seems to work fine until additional mods are installed. I can't for the life of me figure out why this crash occurs. All I can tell from this log and previous ones submitted by various users is that loot pools are somehow being frozen before the `LootTableLoadEvent`.
